name: Settings


on: push

jobs:
  first-job:
    # This job runs on the latest Ubuntu version
    runs-on: ubuntu-latest

    steps:
      # This step checks out the repository
      - name: Checkout
        run: echo "Hello, world!"

  second-job:
    # This job depends on the first job
    needs: first-job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: echo "Hello, world!"
